services:
  - type: web
    name: whatsapp-bot
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: API_URL
        value: https://sua-api.onrender.com/mensagem
    plan: free